/* =============================================
   Export Engine — PDF Report & CSV Download
   ============================================= */

const Exporter = {
    /**
     * Export benchmark results as CSV
     */
    exportCSV(benchmarkData, categoryName) {
        const rows = [['Algorithm', 'Input Size', 'Avg Time (ms)', 'Min Time (ms)', 'Max Time (ms)', 'Variance (ms²)', 'Std Dev (ms)', 'Memory (KB)', 'Detected Complexity']];

        benchmarkData.forEach(algo => {
            const complexity = PerformanceEngine.detectComplexity(algo.results);
            algo.results.forEach(r => {
                rows.push([
                    algo.name,
                    r.inputSize,
                    r.avgTime.toFixed(3),
                    r.minTime.toFixed(3),
                    r.maxTime.toFixed(3),
                    r.variance.toFixed(4),
                    r.stdDev.toFixed(3),
                    r.memoryKB.toFixed(2),
                    complexity
                ]);
            });
        });

        const csv = rows.map(r => r.join(',')).join('\n');
        const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `algoviz_${categoryName}_${new Date().toISOString().slice(0, 10)}.csv`;
        link.click();
        URL.revokeObjectURL(url);
    },

    /**
     * Export benchmark results as PDF report
     */
    async exportPDF(benchmarkData, categoryName) {
        const { jsPDF } = window.jspdf;
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pageWidth = pdf.internal.pageSize.getWidth();
        const margin = 15;
        let y = margin;

        // --- Title ---
        pdf.setFillColor(15, 22, 45);
        pdf.rect(0, 0, pageWidth, 45, 'F');
        pdf.setTextColor(238, 240, 246);
        pdf.setFontSize(22);
        pdf.setFont('helvetica', 'bold');
        pdf.text('AlgoViz — Algorithm Analysis Report', margin, 22);
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'normal');
        pdf.setTextColor(180, 185, 200);
        pdf.text(`Category: ${categoryName}  |  Date: ${new Date().toLocaleString()}`, margin, 33);
        pdf.text(`Algorithms analyzed: ${benchmarkData.length}  |  Generated by AlgoViz`, margin, 40);
        y = 55;

        // --- Charts as images ---
        pdf.setTextColor(30, 30, 50);
        try {
            const timeCanvas = document.getElementById('timeChart');
            if (timeCanvas) {
                const timeImg = timeCanvas.toDataURL('image/png');
                pdf.setFontSize(14);
                pdf.setFont('helvetica', 'bold');
                pdf.text('Execution Time vs Input Size', margin, y);
                y += 5;
                const imgWidth = pageWidth - 2 * margin;
                const imgHeight = imgWidth * 0.5;
                pdf.addImage(timeImg, 'PNG', margin, y, imgWidth, imgHeight);
                y += imgHeight + 10;
            }
        } catch (e) {
            console.warn('Could not capture time chart:', e);
        }

        try {
            const memCanvas = document.getElementById('memoryChart');
            if (memCanvas) {
                if (y + 80 > pdf.internal.pageSize.getHeight() - margin) {
                    pdf.addPage();
                    y = margin;
                }
                const memImg = memCanvas.toDataURL('image/png');
                pdf.setFontSize(14);
                pdf.setFont('helvetica', 'bold');
                pdf.text('Memory Usage Comparison', margin, y);
                y += 5;
                const imgWidth = pageWidth - 2 * margin;
                const imgHeight = imgWidth * 0.5;
                pdf.addImage(memImg, 'PNG', margin, y, imgWidth, imgHeight);
                y += imgHeight + 10;
            }
        } catch (e) {
            console.warn('Could not capture memory chart:', e);
        }

        // --- Data Table ---
        if (y + 30 > pdf.internal.pageSize.getHeight() - margin) {
            pdf.addPage();
            y = margin;
        }

        pdf.setFontSize(14);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(30, 30, 50);
        pdf.text('Benchmark Data', margin, y);
        y += 8;

        // Table headers
        const colWidths = [35, 18, 28, 22, 22, 20, 22]; // sum 167
        const headers = ['Algorithm', 'Input', 'Time ± σ (ms)', 'Min (ms)', 'Max (ms)', 'Mem (KB)', 'Big-O'];

        pdf.setFillColor(240, 242, 248);
        pdf.rect(margin, y - 4, pageWidth - 2 * margin, 8, 'F');
        pdf.setFontSize(7);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(80, 80, 100);

        let x = margin + 1;
        headers.forEach((h, i) => {
            pdf.text(h, x, y);
            x += colWidths[i];
        });
        y += 6;

        // Table rows
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(7);
        pdf.setTextColor(50, 50, 70);

        benchmarkData.forEach(algo => {
            const complexity = PerformanceEngine.detectComplexity(algo.results);
            algo.results.forEach((r, rIdx) => {
                if (y > pdf.internal.pageSize.getHeight() - margin - 5) {
                    pdf.addPage();
                    y = margin;
                }

                if (rIdx % 2 === 0) {
                    pdf.setFillColor(248, 249, 252);
                    pdf.rect(margin, y - 3.5, pageWidth - 2 * margin, 5.5, 'F');
                }

                x = margin + 1;
                const rowData = [
                    algo.name,
                    r.inputSize.toLocaleString(),
                    `${r.avgTime.toFixed(3)} ± ${r.stdDev.toFixed(3)}`,
                    r.minTime.toFixed(3),
                    r.maxTime.toFixed(3),
                    r.memoryKB.toFixed(2),
                    complexity
                ];
                rowData.forEach((cell, i) => {
                    pdf.text(String(cell), x, y);
                    x += colWidths[i];
                });
                y += 5.5;
            });
            y += 2;
        });

        // --- Complexity Insights ---
        if (y + 40 > pdf.internal.pageSize.getHeight() - margin) {
            pdf.addPage();
            y = margin;
        }

        y += 5;
        pdf.setFontSize(14);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(30, 30, 50);
        pdf.text('Complexity Insights', margin, y);
        y += 10;

        const algorithmLibrary = AlgoApp ? AlgoApp.getAlgorithmLibrary() : {};

        benchmarkData.forEach(algo => {
            if (y + 30 > pdf.internal.pageSize.getHeight() - margin) {
                pdf.addPage();
                y = margin;
            }

            const detected = PerformanceEngine.detectComplexity(algo.results);
            const algoInfo = algorithmLibrary[algo.name];

            pdf.setFillColor(245, 243, 255);
            pdf.roundedRect(margin, y - 2, pageWidth - 2 * margin, 24, 2, 2, 'F');

            pdf.setFontSize(10);
            pdf.setFont('helvetica', 'bold');
            pdf.setTextColor(88, 60, 200);
            pdf.text(algo.name, margin + 3, y + 4);

            pdf.setFontSize(9);
            pdf.setFont('helvetica', 'bold');
            pdf.setTextColor(120, 80, 220);
            pdf.text(`Detected: ${detected}`, margin + 3, y + 10);

            if (algoInfo && algoInfo.complexity) {
                pdf.setFont('helvetica', 'normal');
                pdf.setTextColor(80, 80, 100);
                pdf.setFontSize(7.5);
                pdf.text(`Best: ${algoInfo.complexity.best}  |  Avg: ${algoInfo.complexity.average}  |  Worst: ${algoInfo.complexity.worst}  |  Space: ${algoInfo.complexity.space}`, margin + 3, y + 15);

                if (algoInfo.description) {
                    pdf.setFontSize(7);
                    pdf.setTextColor(100, 100, 120);
                    const descLines = pdf.splitTextToSize(algoInfo.description, pageWidth - 2 * margin - 6);
                    pdf.text(descLines, margin + 3, y + 20);
                    y += 24 + (descLines.length - 1) * 3.5 + 4;
                } else {
                    y += 28;
                }
            } else {
                y += 16;
            }
        });

        // Save
        pdf.save(`algoviz_${categoryName}_report_${new Date().toISOString().slice(0, 10)}.pdf`);
    }
};
